/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetomonitoramento;

import java.awt.Color;
import java.util.Random;


/**
 *
 * @author ggoncalves
 */
public class TelaMonitoramento extends javax.swing.JFrame {

    /**
     * Creates new form TelaMonitoramento
     */
    
    public TelaMonitoramento() {
        initComponents();
        
        //Exibir dados aleatórios ao abrir a tela
    Integer cpu = sorteador.nextInt(100)+1;  
    Integer memoria = sorteador.nextInt(100)+1;
    Integer disco = sorteador.nextInt(100)+1;  
    Integer rede = sorteador.nextInt(100)+1;
    Integer cpu1 = sorteador.nextInt(100)+1;  
    Integer memoria1 = sorteador.nextInt(100)+1;
    Integer disco1 = sorteador.nextInt(100)+1;  
    Integer rede1 = sorteador.nextInt(100)+1;
    Integer rh = sorteador.nextInt(100)+1;
    
    pbCPU.setValue(cpu);
    if(cpu <60){
            lbCPU.setForeground(Color.black);
        }
        else if(cpu >= 60 && cpu < 80){
            lbCPU.setForeground(Color.orange);
        }
        else{
            lbCPU.setForeground(Color.red);
        }
    lbCPU.setText(cpu + "%");
    
    pbMemoria.setValue(memoria);
    if (memoria <60){
            lbMemoria.setForeground(Color.black);
        }
        else if (memoria >= 60 && memoria <80){
            lbMemoria.setForeground(Color.orange);
        }
        else{
            lbMemoria.setForeground(Color.red);
        }
    lbMemoria.setText(memoria + "%");
    
    pbDisco.setValue(disco);
    if (disco <60){
            lbDisco.setForeground(Color.black);
        }
        else if (disco >= 60 && disco <80){
            lbDisco.setForeground(Color.orange);
        }
        else{
            lbDisco.setForeground(Color.red);
        }
    lbDisco.setText(disco + "%");
    
    if(rede%2 == 0){
            ckRede.setSelected(true);
            lbRede.setForeground(Color.green);
            lbRede.setText("Ativada");
        }
        else {
            ckRede.setSelected(false);
            lbRede.setForeground(Color.red);
            lbRede.setText("Desativada");
        }
    
    pbCpuServidor.setValue(cpu1);
    if(cpu1 <60){
            lbCPUServidor.setForeground(Color.black);
        }
        else if(cpu1 >= 60 && cpu1 < 80){
            lbCPUServidor.setForeground(Color.orange);
        }
        else{
            lbCPUServidor.setForeground(Color.red);
        }
    lbCPUServidor.setText(cpu1 + "%");
    
    pbMemoriaServidor.setValue(memoria1);
    if (memoria1 <60){
            lbMemoriaServidor.setForeground(Color.black);
        }
        else if (memoria1 >= 60 && memoria1 <80){
            lbMemoriaServidor.setForeground(Color.orange);
        }
        else{
            lbMemoriaServidor.setForeground(Color.red);
        }
    lbMemoriaServidor.setText(memoria1 + "%");
    
    pbDiscoServidor.setValue(disco1);
        
        if (disco1 <60){
            lbDiscoServidor.setForeground(Color.black);
        }
        else if (disco1 >= 60 && disco1 <80){
            lbDiscoServidor.setForeground(Color.orange);
        }
        else{
            lbDiscoServidor.setForeground(Color.red);
        }
        lbDiscoServidor.setText(disco1 + "%");
        
    if(rede1%2 == 0){
            ckRedeServidor.setSelected(true);
            lbRedeServidor.setForeground(Color.green);
            lbRedeServidor.setText("Ativada");
        }
        else {
            ckRedeServidor.setSelected(false);
            lbRedeServidor.setForeground(Color.red);
            lbRedeServidor.setText("Desativada");
        }
        
        if(cpu1 < 90 && memoria1 <90 && disco1 <90 && rede1%2 == 0){
            ckRH.setSelected(true);
            lbRH.setForeground(Color.green);
            lbRH.setText("Online");
        }
        else{
            ckRH.setSelected(false);
            lbRH.setForeground(Color.red);
            lbRH.setText("Offline");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pbCPU = new javax.swing.JProgressBar();
        lbCPU = new javax.swing.JLabel();
        btAtualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pbMemoria = new javax.swing.JProgressBar();
        lbMemoria = new javax.swing.JLabel();
        pbDisco = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        lbDisco = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ckRede = new javax.swing.JCheckBox();
        lbRede = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pbCpuServidor = new javax.swing.JProgressBar();
        lbCPUServidor = new javax.swing.JLabel();
        btAtualizarServidor = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pbMemoriaServidor = new javax.swing.JProgressBar();
        lbMemoriaServidor = new javax.swing.JLabel();
        pbDiscoServidor = new javax.swing.JProgressBar();
        lbDiscoServidor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ckRedeServidor = new javax.swing.JCheckBox();
        lbRedeServidor = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ckRH = new javax.swing.JCheckBox();
        lbRH = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfQtdPC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfServidor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfWindows = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        b = new javax.swing.JLabel();
        tfLinux = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfWindowsS = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfLinuxS = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        er = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        lbMensagem = new javax.swing.JLabel();
        lbMensalidade = new javax.swing.JLabel();
        lbSemestral = new javax.swing.JLabel();
        lbTrimestral = new javax.swing.JLabel();
        lbAnual = new javax.swing.JLabel();
        lbMensagem2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText(" Monitoramento PC ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel3.setText("CPU:");

        lbCPU.setOpaque(true);

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel4.setText("Memória:");

        lbMemoria.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel5.setText("Disco:");

        lbDisco.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel6.setText("Rede:");

        ckRede.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        ckRede.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btAtualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pbCPU, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(pbMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ckRede)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbRede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(22, 22, 22)
                            .addComponent(pbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(pbCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(pbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ckRede)
                    .addComponent(lbRede, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addComponent(btAtualizar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PC", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText(" Monitoramento Servidor ");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel7.setText("CPU:");

        lbCPUServidor.setOpaque(true);

        btAtualizarServidor.setText("Atualizar");
        btAtualizarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarServidorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel8.setText("Memória:");

        lbMemoriaServidor.setOpaque(true);

        lbDiscoServidor.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel9.setText("Disco:");

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel10.setText("Rede:");

        ckRedeServidor.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        ckRedeServidor.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel11.setText("Sistema RH:");

        ckRH.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        ckRH.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(9, 9, 9)
                        .addComponent(ckRH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbRH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel9))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(ckRedeServidor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbRedeServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(pbDiscoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDiscoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pbMemoriaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(pbCpuServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMemoriaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCPUServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btAtualizarServidor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbCPUServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCpuServidor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbMemoriaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMemoriaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pbDiscoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbDiscoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(ckRedeServidor)
                    .addComponent(lbRedeServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(ckRH)
                    .addComponent(lbRH, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(btAtualizarServidor)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Servidor", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setText("Simulação Financeira");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("Quantidade de Computadores Monitorados:");

        jLabel14.setText("Quantidade de Servidores Monitorados:");

        jLabel15.setText("Quantos Computadores são Windows?");

        b.setText("Quantos Computadores são Linux?");

        jLabel17.setText("Quantos Servidores são Windows?");

        jLabel18.setText("Quantos Servidores são Linux?");

        jLabel19.setText("Mensal:");

        jLabel20.setText("Trimestral:");

        jLabel21.setText("Semestral:");

        er.setText("Anual:");

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        lbMensalidade.setBackground(new java.awt.Color(255, 255, 255));
        lbMensalidade.setOpaque(true);

        lbSemestral.setBackground(new java.awt.Color(255, 255, 255));
        lbSemestral.setOpaque(true);

        lbTrimestral.setBackground(new java.awt.Color(255, 255, 255));
        lbTrimestral.setOpaque(true);

        lbAnual.setBackground(new java.awt.Color(255, 255, 255));
        lbAnual.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLinuxS, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfWindowsS)
                                    .addComponent(tfServidor)
                                    .addComponent(tfQtdPC)
                                    .addComponent(tfLinux, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(tfWindows)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbMensalidade, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(lbSemestral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(er, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbAnual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbTrimestral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lbMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 21, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbMensagem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfQtdPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfWindows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b)
                    .addComponent(tfLinux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMensagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfWindowsS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfLinuxS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(lbTrimestral, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(er, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSemestral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAnual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addComponent(lbMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Financeiro", jPanel3);

        jDesktopPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Random sorteador = new Random();

    
    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
    Integer cpu = sorteador.nextInt(100)+1;  
    Integer memoria = sorteador.nextInt(100)+1;
    Integer disco = sorteador.nextInt(100)+1;  
    Integer rede = sorteador.nextInt(100)+1;  
    
        pbCPU.setValue(cpu);
        
        if(cpu <60){
            lbCPU.setForeground(Color.black);
        }
        else if(cpu >= 60 && cpu < 80){
            lbCPU.setForeground(Color.orange);
        }
        else{
            lbCPU.setForeground(Color.red);
        }
        lbCPU.setText(cpu + "%");
        
        pbMemoria.setValue(memoria);
        
        if (memoria <60){
            lbMemoria.setForeground(Color.black);
        }
        else if (memoria >= 60 && memoria <80){
            lbMemoria.setForeground(Color.orange);
        }
        else{
            lbMemoria.setForeground(Color.red);
        }
        lbMemoria.setText(memoria + "%");
        
        pbDisco.setValue(disco);
        
        if (disco <60){
            lbDisco.setForeground(Color.black);
        }
        else if (disco >= 60 && disco <80){
            lbDisco.setForeground(Color.orange);
        }
        else{
            lbDisco.setForeground(Color.red);
        }
        lbDisco.setText(disco + "%");
        
        if(rede%2 == 0){
            ckRede.setSelected(true);
            lbRede.setForeground(Color.green);
            lbRede.setText("Ativada");
        }
        else {
            ckRede.setSelected(false);
            lbRede.setForeground(Color.red);
            lbRede.setText("Desativada");
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btAtualizarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarServidorActionPerformed
        Integer cpu = sorteador.nextInt(100)+1;
        Integer memoria = sorteador.nextInt(100)+1;
        Integer disco = sorteador.nextInt(100)+1;
        Integer rede = sorteador.nextInt(100)+1;
        Integer rh = sorteador.nextInt(100)+1;

        pbCpuServidor.setValue(cpu);

        if(cpu <60){
            lbCPUServidor.setForeground(Color.black);
        }
        else if(cpu >= 60 && cpu < 80){
            lbCPUServidor.setForeground(Color.orange);
        }
        else{
            lbCPUServidor.setForeground(Color.red);
        }
        lbCPUServidor.setText(cpu + "%");

        pbMemoriaServidor.setValue(memoria);

        if (memoria <60){
            lbMemoriaServidor.setForeground(Color.black);
        }
        else if (memoria >= 60 && memoria <80){
            lbMemoriaServidor.setForeground(Color.orange);
        }
        else{
            lbMemoriaServidor.setForeground(Color.red);
        }
        lbMemoriaServidor.setText(memoria + "%");

        pbDiscoServidor.setValue(disco);

        if (disco <60){
            lbDiscoServidor.setForeground(Color.black);
        }
        else if (disco >= 60 && disco <80){
            lbDiscoServidor.setForeground(Color.orange);
        }
        else{
            lbDiscoServidor.setForeground(Color.red);
        }
        lbDiscoServidor.setText(disco + "%");

        if(rede%2 == 0){
            ckRedeServidor.setSelected(true);
            lbRedeServidor.setForeground(Color.green);
            lbRedeServidor.setText("Ativada");
        }
        else {
            ckRedeServidor.setSelected(false);
            lbRedeServidor.setForeground(Color.red);
            lbRedeServidor.setText("Desativada");
        }

        if(cpu < 90 && memoria <90 && disco <90 && rede%2 == 0){
            ckRH.setSelected(true);
            lbRH.setForeground(Color.green);
            lbRH.setText("Online");
        }
        else{
            ckRH.setSelected(false);
            lbRH.setForeground(Color.red);
            lbRH.setText("Offline");
        }
    }//GEN-LAST:event_btAtualizarServidorActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        Integer qtdPc = Integer.valueOf(tfQtdPC.getText());
        Integer pcWindows = Integer.valueOf(tfWindows.getText());
        Integer pcLinux = Integer.valueOf(tfLinux.getText());
        Integer servidor = Integer.valueOf(tfServidor.getText());
        Integer servWindows = Integer.valueOf(tfWindowsS.getText());
        Integer servLinux = Integer.valueOf(tfLinuxS.getText());
        Integer so = pcLinux + pcWindows;
        Integer soServ = servWindows + servLinux;
        Double total;
        Double precoWind = 60.0;
        Double precoLinux = 50.0;
        Double precoServWind = 120.0;
        Double precoServLinux = 100.0;

        if(qtdPc < so && servidor < soServ){
            lbMensagem.setText("");
            lbMensagem2.setText("");
            lbMensagem.setText("<HTML> Quantidade de servidor é menor que a"
                + " <br>quantidade de sistemas operacionais. </HTML>");
            lbMensagem.setForeground(Color.red);
            lbMensagem2.setText("<HTML> Quantidade de computador é menor que a"
                + " <br>quantidade de sistemas operacionais. </HTML>");
            lbMensagem2.setForeground(Color.red);
            lbAnual.setText("");
            lbMensalidade.setText("");
            lbSemestral.setText("");
            lbTrimestral.setText("");
        }
        else if (qtdPc > so && servidor > soServ){
            lbMensagem.setText("");
            lbMensagem2.setText("");
            lbMensagem.setText("<HTML> Quantidade de servidor é maior que a"
                + " <br>quantidade de sistemas operacionais. </HTML>");
            lbMensagem.setForeground(Color.red);
            lbMensagem2.setText("<HTML> Quantidade de computador é maior que a"
                + " <br>quantidade de sistemas operacionais. </HTML>");
            lbMensagem2.setForeground(Color.red);
            lbAnual.setText("");
            lbMensalidade.setText("");
            lbSemestral.setText("");
            lbTrimestral.setText("");
        }
        else if (qtdPc < so && servidor > soServ){
            lbMensagem.setText("");
            lbMensagem2.setText("");
            lbMensagem.setText("<HTML> Quantidade de servidor é maior que a"
                + " <br>quantidade de sistemas operacionais. </HTML>");
            lbMensagem.setForeground(Color.red);
            lbMensagem2.setText("<HTML> Quantidade de computador é menor que a"
                + " <br>quantidade de sistemas operacionais. </HTML>");
            lbMensagem2.setForeground(Color.red);
            lbAnual.setText("");
            lbMensalidade.setText("");
            lbSemestral.setText("");
            lbTrimestral.setText("");
        }
        else if (qtdPc > so && servidor < soServ){
            lbMensagem.setText("");
            lbMensagem2.setText("");
            lbMensagem.setText("<HTML> Quantidade de servidor é menor que a"
                + " <br>quantidade de sistemas operacionais. </HTML>");
            lbMensagem.setForeground(Color.red);
            lbMensagem2.setText("<HTML> Quantidade de computador é maior que a"
                + " <br>quantidade de sistemas operacionais. </HTML>");
            lbMensagem2.setForeground(Color.red);
            lbAnual.setText("");
            lbMensalidade.setText("");
            lbSemestral.setText("");
            lbTrimestral.setText("");
        }
        else if (qtdPc > so){
            lbMensagem.setText("");
            lbMensagem2.setText("");
            lbMensagem2.setText("<HTML> Quantidade de computadores é maior que a quantidade"
                    + " de sistemas operacionais.</HTML>");
            lbMensagem2.setForeground(Color.red);
            lbAnual.setText("");
            lbMensalidade.setText("");
            lbSemestral.setText("");
            lbTrimestral.setText("");
        }
        else if (servidor > soServ){
            lbMensagem.setText("");
            lbMensagem2.setText("");
            lbMensagem.setText("<HTML> Quantidade de servidor é maior que a quantidade"
                    + " de sistemas operacionais.</HTML>");
            lbMensagem.setForeground(Color.red);
            lbAnual.setText("");
            lbMensalidade.setText("");
            lbSemestral.setText("");
            lbTrimestral.setText("");
        }
        else if(qtdPc < so){
            lbMensagem2.setText("");
            lbMensagem.setText("");
            lbMensagem2.setText("<HTML> Quantidade de computadores é menor que a quantidade"
                    + " de sistemas operacionais.</HTML>");
            lbMensagem2.setForeground(Color.red);
            lbAnual.setText("");
            lbMensalidade.setText("");
            lbSemestral.setText("");
            lbTrimestral.setText("");
        }
        else if(servidor < soServ){
            lbMensagem.setText("");
            lbMensagem2.setText("");
            lbMensagem.setText("<HTML> Quantidade de servidor é menor que a quantidade"
                    + " de sistemas operacionais.</HTML>");
            lbMensagem.setForeground(Color.red);
            lbAnual.setText("");
            lbMensalidade.setText("");
            lbSemestral.setText("");
            lbTrimestral.setText("");
        }
        else{
            lbMensagem.setText("");
            lbMensagem2.setText("");
            total = (pcWindows * precoWind) + (pcLinux * precoLinux) + 
                    (servLinux * precoServLinux) + (servWindows * precoServWind);
            lbMensalidade.setText(String.format("R$: %.2f", total));
            Double descTri = ((total * 3) * 5) /100;
            lbTrimestral.setText(String.format("R$: %.2f",  (total * 3) - descTri));
            Double descSemes = ((total * 6) * 10) /100;
            lbSemestral.setText(String.format("R$: %.2f", (total * 6) - descSemes));
            Double descAnual = ((total * 12) * 15) /100;
            lbAnual.setText(String.format("R$: %.2f", (total * 12) - descAnual));
        }

    }//GEN-LAST:event_btCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMonitoramento().setVisible(true);
            }
        });
                
     
            
               
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btAtualizarServidor;
    private javax.swing.JButton btCalcular;
    private javax.swing.JCheckBox ckRH;
    private javax.swing.JCheckBox ckRede;
    private javax.swing.JCheckBox ckRedeServidor;
    private javax.swing.JLabel er;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbAnual;
    private javax.swing.JLabel lbCPU;
    private javax.swing.JLabel lbCPUServidor;
    private javax.swing.JLabel lbDisco;
    private javax.swing.JLabel lbDiscoServidor;
    private javax.swing.JLabel lbMemoria;
    private javax.swing.JLabel lbMemoriaServidor;
    private javax.swing.JLabel lbMensagem;
    private javax.swing.JLabel lbMensagem2;
    private javax.swing.JLabel lbMensalidade;
    private javax.swing.JLabel lbRH;
    private javax.swing.JLabel lbRede;
    private javax.swing.JLabel lbRedeServidor;
    private javax.swing.JLabel lbSemestral;
    private javax.swing.JLabel lbTrimestral;
    private javax.swing.JProgressBar pbCPU;
    private javax.swing.JProgressBar pbCpuServidor;
    private javax.swing.JProgressBar pbDisco;
    private javax.swing.JProgressBar pbDiscoServidor;
    private javax.swing.JProgressBar pbMemoria;
    private javax.swing.JProgressBar pbMemoriaServidor;
    private javax.swing.JTextField tfLinux;
    private javax.swing.JTextField tfLinuxS;
    private javax.swing.JTextField tfQtdPC;
    private javax.swing.JTextField tfServidor;
    private javax.swing.JTextField tfWindows;
    private javax.swing.JTextField tfWindowsS;
    // End of variables declaration//GEN-END:variables
}
