/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.full.sight.oshi;

import oshi.PlatformEnum;

/**
 *
 * @author Aluno
 */
public class TelaMonitoramentoFS extends javax.swing.JFrame {

    MonitoramentoFS tela = new MonitoramentoFS();

    public TelaMonitoramentoFS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pCpu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lbSO = new javax.swing.JLabel();
        lbFrequenciaCPU = new javax.swing.JLabel();
        lbThreads = new javax.swing.JLabel();
        lbModelo = new javax.swing.JLabel();
        lbPortasLogicas = new javax.swing.JLabel();
        lbPortasLogicas1 = new javax.swing.JLabel();
        pRam = new javax.swing.JPanel();
        lbMemoriaUtilizada = new javax.swing.JLabel();
        lbMemoriaTotal = new javax.swing.JLabel();
        lbMemoriaDisponivel = new javax.swing.JLabel();
        pbMemoriaUtilizada = new javax.swing.JProgressBar();
        pbMemoriaDisponivel = new javax.swing.JProgressBar();
        pDisco = new javax.swing.JPanel();
        lbUsoDisco = new javax.swing.JLabel();
        lbTeste = new javax.swing.JLabel();
        pRede = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pCpu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Buscar dados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbSO.setText("Sistema Operacional:");

        lbFrequenciaCPU.setText("Frequência da CPU:");

        lbThreads.setText("Quantidade de Threads:");

        lbModelo.setText("Modelo do Processador:");

        lbPortasLogicas.setText("Quantidade de Portas lógicas:");

        lbPortasLogicas1.setText("Quantidade de Processos: ");

        javax.swing.GroupLayout pCpuLayout = new javax.swing.GroupLayout(pCpu);
        pCpu.setLayout(pCpuLayout);
        pCpuLayout.setHorizontalGroup(
            pCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCpuLayout.createSequentialGroup()
                .addGroup(pCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCpuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbSO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pCpuLayout.createSequentialGroup()
                        .addGroup(pCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pCpuLayout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jButton1))
                            .addGroup(pCpuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFrequenciaCPU)
                                    .addComponent(lbThreads)
                                    .addComponent(lbModelo)
                                    .addComponent(lbPortasLogicas))))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pCpuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPortasLogicas1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCpuLayout.setVerticalGroup(
            pCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCpuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSO)
                .addGap(26, 26, 26)
                .addComponent(lbModelo)
                .addGap(18, 18, 18)
                .addComponent(lbFrequenciaCPU)
                .addGap(18, 18, 18)
                .addComponent(lbThreads)
                .addGap(18, 18, 18)
                .addComponent(lbPortasLogicas)
                .addGap(18, 18, 18)
                .addComponent(lbPortasLogicas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("CPU", pCpu);

        lbMemoriaUtilizada.setText("Memória Utlizada:");

        lbMemoriaTotal.setText("Memória total:");

        lbMemoriaDisponivel.setText("Memória Disponível:");

        pbMemoriaUtilizada.setMaximum(1000000000);

        pbMemoriaDisponivel.setMaximum(200000000);
        pbMemoriaDisponivel.setToolTipText("");

        javax.swing.GroupLayout pRamLayout = new javax.swing.GroupLayout(pRam);
        pRam.setLayout(pRamLayout);
        pRamLayout.setHorizontalGroup(
            pRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRamLayout.createSequentialGroup()
                        .addGroup(pRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMemoriaUtilizada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMemoriaTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMemoriaDisponivel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                        .addGap(163, 163, 163))
                    .addGroup(pRamLayout.createSequentialGroup()
                        .addComponent(pbMemoriaUtilizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pRamLayout.createSequentialGroup()
                        .addComponent(pbMemoriaDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pRamLayout.setVerticalGroup(
            pRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRamLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbMemoriaUtilizada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbMemoriaUtilizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbMemoriaDisponivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pbMemoriaDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbMemoriaTotal)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RAM", pRam);

        lbUsoDisco.setText("Uso do Disco:");

        lbTeste.setText("teste");

        javax.swing.GroupLayout pDiscoLayout = new javax.swing.GroupLayout(pDisco);
        pDisco.setLayout(pDiscoLayout);
        pDiscoLayout.setHorizontalGroup(
            pDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUsoDisco)
                    .addComponent(lbTeste))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        pDiscoLayout.setVerticalGroup(
            pDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsoDisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTeste)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DISCO", pDisco);

        javax.swing.GroupLayout pRedeLayout = new javax.swing.GroupLayout(pRede);
        pRede.setLayout(pRedeLayout);
        pRedeLayout.setHorizontalGroup(
            pRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        pRedeLayout.setVerticalGroup(
            pRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("REDE", pRede);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Labels da Memória
        /*
        pbMemoriaUtilizada.setValue(tela.verMemoriaUsadaPb());

        pbMemoriaDisponivel.setValue(tela.verMemoriaPb());
        */
        lbMemoriaUtilizada.setText(tela.verMemoriaUsada(tela.hal.getMemory()));

        lbMemoriaDisponivel.setText(tela.verMemoriaDisponivel(tela.hal.getMemory()));

        lbMemoriaTotal.setText(tela.verMemoriaTotal(tela.hal.getMemory()));

        
        //Labels do CPU
        lbFrequenciaCPU.setText(tela.verUsoCPU(tela.hal.getProcessor()));

        lbSO.setText(tela.verSO(PlatformEnum.LINUX));

        lbThreads.setText(tela.verThreads());

        lbModelo.setText(tela.verProcessador());

        lbPortasLogicas.setText(tela.verPortasLogicas());

        lbPortasLogicas1.setText(tela.verQtdProcessos());
        
        
        //Labels do Disco
        lbUsoDisco.setText(tela.verUsoDisco());
        
        lbTeste.setText(tela.verDiscoTeste());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramentoFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramentoFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramentoFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramentoFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMonitoramentoFS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbFrequenciaCPU;
    private javax.swing.JLabel lbMemoriaDisponivel;
    private javax.swing.JLabel lbMemoriaTotal;
    private javax.swing.JLabel lbMemoriaUtilizada;
    private javax.swing.JLabel lbModelo;
    private javax.swing.JLabel lbPortasLogicas;
    private javax.swing.JLabel lbPortasLogicas1;
    private javax.swing.JLabel lbSO;
    private javax.swing.JLabel lbTeste;
    private javax.swing.JLabel lbThreads;
    private javax.swing.JLabel lbUsoDisco;
    private javax.swing.JPanel pCpu;
    private javax.swing.JPanel pDisco;
    private javax.swing.JPanel pRam;
    private javax.swing.JPanel pRede;
    private javax.swing.JProgressBar pbMemoriaDisponivel;
    private javax.swing.JProgressBar pbMemoriaUtilizada;
    // End of variables declaration//GEN-END:variables
}
