/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.full.sight.oshi;

//libs para atualizar em tempo real
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
//lib para mostrar nome do SO
import oshi.PlatformEnum;

/**
 *
 * @author Aluno
 */
public class TelaMonitoramentoFS extends javax.swing.JFrame {

    MonitoramentoFS tela = new MonitoramentoFS();
    Timer t;

    void labelsMemoria() {
        t = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
        /*
        pbMemoriaUtilizada.setValue(tela.verMemoriaUsadaPb());

        pbMemoriaDisponivel.setValue(tela.verMemoriaPb());
         */
        lbMemoriaUtilizada.setText(tela.verMemoriaUsada(tela.hal.getMemory()));

        lbMemoriaDisponivel.setText(tela.verMemoriaDisponivel(tela.hal.getMemory()));

        lbMemoriaTotal.setText(tela.verMemoriaTotal(tela.hal.getMemory()));
        }
        });

        t.start();
    }

    void labelsCpu() {
        t = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                lbPorcentagemCpu.setText(tela.verPorcentagemCpu());

                lbFrequenciaCPU.setText(tela.verUsoCPU(tela.hal.getProcessor()));

                lbSO.setText(tela.verSO(PlatformEnum.LINUX));

                lbThreads.setText(tela.verThreads());

                lbPortasLogicas.setText(tela.verPortasLogicas());

                lbPortasLogicas1.setText(tela.verQtdProcessos());
                
            }
        });
                taProcessos.setText(tela.printProcesses(tela.os, tela.hal.getMemory()));

        t.start();

    }

    void labelsDisco() {
        lbEspacoLivre.setText(tela.verEspacoLivre());

        lbEspacoUtilizado.setText(tela.verEspacoUtilizado());

        lbEspacoTotal.setText(tela.verEspacoTotal());
    }

    public TelaMonitoramentoFS() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnRam3 = new javax.swing.JPanel();
        lbMemoriaTotal4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbMemoriaUtilizada5 = new javax.swing.JLabel();
        lbMemoriaDisponivel4 = new javax.swing.JLabel();
        pnDisco2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbEspacoUtilizado2 = new javax.swing.JLabel();
        lbEspacoLivre2 = new javax.swing.JLabel();
        lbEspacoTotal2 = new javax.swing.JLabel();
        pnCpu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbPortasLogicas2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbFrequenciaCPU1 = new javax.swing.JLabel();
        lbPorcentagemCpu1 = new javax.swing.JLabel();
        lbThreads1 = new javax.swing.JLabel();
        lbPortasLogicas3 = new javax.swing.JLabel();
        lbSO = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taProcessos = new javax.swing.JTextArea();
        btExecutar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        pnRam3.setBackground(new java.awt.Color(204, 204, 255));

        lbMemoriaTotal4.setForeground(new java.awt.Color(255, 51, 51));
        lbMemoriaTotal4.setText("Memória total:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("RAM");

        lbMemoriaUtilizada5.setForeground(new java.awt.Color(255, 51, 51));
        lbMemoriaUtilizada5.setText("Memória Utlizada:");

        lbMemoriaDisponivel4.setForeground(new java.awt.Color(255, 51, 51));
        lbMemoriaDisponivel4.setText("Memória Disponível:");

        javax.swing.GroupLayout pnRam3Layout = new javax.swing.GroupLayout(pnRam3);
        pnRam3.setLayout(pnRam3Layout);
        pnRam3Layout.setHorizontalGroup(
            pnRam3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRam3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnRam3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbMemoriaUtilizada5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMemoriaDisponivel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMemoriaTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnRam3Layout.setVerticalGroup(
            pnRam3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRam3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(lbMemoriaUtilizada5)
                .addGap(11, 11, 11)
                .addComponent(lbMemoriaDisponivel4)
                .addGap(11, 11, 11)
                .addComponent(lbMemoriaTotal4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnDisco2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("DISCO");

        lbEspacoUtilizado2.setForeground(new java.awt.Color(255, 51, 51));
        lbEspacoUtilizado2.setText("Espaço Utilizado:");

        lbEspacoLivre2.setForeground(new java.awt.Color(255, 51, 51));
        lbEspacoLivre2.setText("Espaço livre: ");

        lbEspacoTotal2.setBackground(new java.awt.Color(0, 0, 0));
        lbEspacoTotal2.setForeground(new java.awt.Color(255, 51, 51));
        lbEspacoTotal2.setText("Espaço total: ");

        javax.swing.GroupLayout pnDisco2Layout = new javax.swing.GroupLayout(pnDisco2);
        pnDisco2.setLayout(pnDisco2Layout);
        pnDisco2Layout.setHorizontalGroup(
            pnDisco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDisco2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDisco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lbEspacoUtilizado2)
                    .addComponent(lbEspacoLivre2)
                    .addComponent(lbEspacoTotal2))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        pnDisco2Layout.setVerticalGroup(
            pnDisco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDisco2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(lbEspacoUtilizado2)
                .addGap(11, 11, 11)
                .addComponent(lbEspacoLivre2)
                .addGap(13, 13, 13)
                .addComponent(lbEspacoTotal2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnCpu.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setText("%");

        lbPortasLogicas2.setForeground(new java.awt.Color(255, 51, 51));
        lbPortasLogicas2.setText("Quantidade de Portas lógicas:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("CPU");

        lbFrequenciaCPU1.setForeground(new java.awt.Color(255, 51, 51));
        lbFrequenciaCPU1.setText("Frequência da CPU:");

        lbPorcentagemCpu1.setForeground(new java.awt.Color(255, 51, 51));
        lbPorcentagemCpu1.setText("Uso atual da CPU:");

        lbThreads1.setForeground(new java.awt.Color(255, 51, 51));
        lbThreads1.setText("Quantidade de Threads:");

        lbPortasLogicas3.setForeground(new java.awt.Color(255, 51, 51));
        lbPortasLogicas3.setText("Quantidade de Processos: ");

        javax.swing.GroupLayout pnCpuLayout = new javax.swing.GroupLayout(pnCpu);
        pnCpu.setLayout(pnCpuLayout);
        pnCpuLayout.setHorizontalGroup(
            pnCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCpuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPorcentagemCpu1)
                    .addComponent(lbPortasLogicas2)
                    .addComponent(lbThreads1)
                    .addComponent(lbPortasLogicas3)
                    .addGroup(pnCpuLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel6))
                    .addComponent(lbFrequenciaCPU1))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnCpuLayout.setVerticalGroup(
            pnCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCpuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(pnCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPorcentagemCpu1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnCpuLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lbPortasLogicas2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCpuLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbThreads1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCpuLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lbPortasLogicas3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnCpuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbFrequenciaCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbSO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSO.setText("Sistema Operacional:");

        taProcessos.setColumns(20);
        taProcessos.setRows(5);
        jScrollPane1.setViewportView(taProcessos);

        btExecutar.setBackground(new java.awt.Color(0, 0, 0));
        btExecutar.setForeground(new java.awt.Color(102, 0, 0));
        btExecutar.setText("Buscar dados");
        btExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSO)
                            .addComponent(pnCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnRam3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnDisco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(btExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbSO)
                        .addGap(24, 24, 24)
                        .addComponent(pnCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnRam3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnDisco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExecutarActionPerformed
        labelsMemoria();
        labelsCpu();
        labelsDisco();
    }//GEN-LAST:event_btExecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramentoFS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramentoFS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramentoFS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramentoFS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMonitoramentoFS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExecutar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEspacoLivre2;
    private javax.swing.JLabel lbEspacoTotal2;
    private javax.swing.JLabel lbEspacoUtilizado2;
    private javax.swing.JLabel lbFrequenciaCPU1;
    private javax.swing.JLabel lbMemoriaDisponivel1;
    private javax.swing.JLabel lbMemoriaDisponivel4;
    private javax.swing.JLabel lbMemoriaDisponivel5;
    private javax.swing.JLabel lbMemoriaTotal1;
    private javax.swing.JLabel lbMemoriaTotal4;
    private javax.swing.JLabel lbMemoriaTotal5;
    private javax.swing.JLabel lbMemoriaUtilizada2;
    private javax.swing.JLabel lbMemoriaUtilizada5;
    private javax.swing.JLabel lbMemoriaUtilizada6;
    private javax.swing.JLabel lbPorcentagemCpu1;
    private javax.swing.JLabel lbPortasLogicas2;
    private javax.swing.JLabel lbPortasLogicas3;
    private javax.swing.JLabel lbSO;
    private javax.swing.JLabel lbThreads1;
    private javax.swing.JPanel pnCpu;
    private javax.swing.JPanel pnDisco2;
    private javax.swing.JPanel pnRam;
    private javax.swing.JPanel pnRam3;
    private javax.swing.JPanel pnRam4;
    private javax.swing.JTextArea taProcessos;
    // End of variables declaration//GEN-END:variables
}
