/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.pesquisainovacao;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author guilherme.lima
 */
public class projetoPI extends javax.swing.JFrame {

    /** Creates new form projetoPI */
    public projetoPI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The cont
     * ent of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cpuBarra = new javax.swing.JProgressBar();
        memoriaBarra = new javax.swing.JProgressBar();
        discoBarra = new javax.swing.JProgressBar();
        cpuLab = new javax.swing.JLabel();
        memoriaLab = new javax.swing.JLabel();
        discoLab = new javax.swing.JLabel();
        rede = new javax.swing.JLabel();
        redebox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("CPU");

        jLabel2.setText("Memória");

        jLabel3.setText("Disco");

        cpuLab.setText("jLabel4");

        memoriaLab.setText("jLabel5");

        discoLab.setText("jLabel6");

        redebox.setText("Conectado via cabo");
        redebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redeboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rede)
                        .addComponent(jButton1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(discoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(discoLab))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(memoriaBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(memoriaLab))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cpuBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cpuLab))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(redebox)
                        .addGap(190, 190, 190)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpuLab)
                    .addComponent(jLabel1)
                    .addComponent(cpuBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memoriaLab)
                            .addComponent(memoriaBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(discoLab, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(discoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(rede)
                .addGap(18, 18, 18)
                .addComponent(redebox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Random sorte = new Random();
       Integer porcentagem = sorte.nextInt(100);         
       cpuLab.setText(porcentagem+"%");
       cpuBarra.setValue(porcentagem);
       
       
     // Integer CPU = cpuLab.getText
       Integer Barra= cpuBarra.getValue();
       
       if (Barra >=60 && Barra<80) { 
          cpuLab.setForeground(Color.YELLOW);
       } else if (Barra >=80){
           cpuLab.setForeground(Color.RED);
       } else { 
           cpuLab.setForeground(Color.GREEN);
       }
           
       
       
       
       Random sorte2 = new Random();
       Integer porcentagem2 = sorte2.nextInt(100);         
       memoriaLab.setText(porcentagem2+"%");
       memoriaBarra.setValue(porcentagem2);
       
        Integer Barra2= memoriaBarra.getValue();
       
       if (Barra2 >=60 && Barra2<80) { 
          memoriaLab.setForeground(Color.YELLOW);
       } else if (Barra2 >=80){
           memoriaLab.setForeground(Color.RED);
       } else { 
           memoriaLab.setForeground(Color.GREEN);
       }
       
       
       Random sorte3 = new Random();
       Integer porcentagem3 = sorte3.nextInt(100);         
       discoLab.setText(porcentagem3+"%");
       discoBarra.setValue(porcentagem3);
       
        Integer Barra3= discoBarra.getValue();
       
       if (Barra3 >=60 && Barra3<80) { 
          discoLab.setForeground(Color.YELLOW);
       } else if (Barra3 >=80){
          discoLab.setForeground(Color.RED);
       } else { 
          discoLab.setForeground(Color.GREEN);
       }
       
       
       if ( Barra >=80 && Barra2 >= 80 && Barra3 >= 80){
           rede.setText("Desconectado da Rede");
                   rede.setForeground(Color.red);
       } else {
           rede.setText("conectado em Rede");
           rede.setForeground(Color.GREEN);
       }
       
       if (redebox.isSelected()){
           redebox.setForeground(Color.GREEN);
       } else {
           redebox.setForeground(Color.red);
       }
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void redeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redeboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redeboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projetoPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projetoPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projetoPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projetoPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projetoPI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar cpuBarra;
    private javax.swing.JLabel cpuLab;
    private javax.swing.JProgressBar discoBarra;
    private javax.swing.JLabel discoLab;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar memoriaBarra;
    private javax.swing.JLabel memoriaLab;
    private javax.swing.JLabel rede;
    private javax.swing.JCheckBox redebox;
    // End of variables declaration//GEN-END:variables

}
